import express from "express";
import cors from "cors";

const app = express();
app.use(cors());
app.use(express.json());

//app.use("/api/v1/football", football);
//app.use("*", (req, res) => res.status(404).json({ error: "not found" }));

const chelsea = {
  id: "1",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/18/18.png",
  nome: "Chelsea",
  treinador: "Delsin",
};
const realMadrid = {
  id: "2",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/12/3468.png",
  nome: "Real Madrid",
  treinador: "Danikro",
};
const manchesterCity = {
  id: "3",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/9/9.png",
  nome: "Manchester City",
  treinador: "Lil Dani",
};
const juventus = {
  id: "4",
  logo: "https://logodetimes.com/times/juventus-football-club/juventus-football-club-2048.png",
  nome: "Juventus",
  treinador: "Edu",
};
const psg = {
  id: "5",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/15/591.png",
  nome: "Paris Saint Germain",
  treinador: "Borraxa Diniz",
};
const barcelona = {
  id: "6",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/19/83.png",
  nome: "Barcelona",
  treinador: "Rafa",
};
const bayern = {
  id: "7",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/23/503.png",
  nome: "Bayern Munchen",
  treinador: "PH",
};
const liverpool = {
  id: "8",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/8/8.png",
  nome: "Liverpool",
  treinador: "Klopp LaminaZ",
};
const tottenham = {
  id: "9",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/6/6.png",
  nome: "Tottenham",
  treinador: "Crazzy",
};
const manchesterUnited = {
  id: "10",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/14/14.png",
  nome: "Manchester United",
  treinador: "Baitzera",
};
const inter = {
  id: "11",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/18/2930.png",
  nome: "Inter",
  treinador: "Vaga",
};
const arsenal = {
  id: "12",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/19/19.png",
  nome: "Arsenal",
  treinador: "Renan",
};
const leipzig = {
  id: "13",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/21/277.png",
  nome: "RB Leipzig",
  treinador: "Erick",
};
const dortmund = {
  id: "14",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/4/68.png",
  nome: "Borussia Dortmund",
  treinador: "Michel",
};
const marseille = {
  id: "15",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/12/44.png",
  nome: "Olympique Marseille",
  treinador: "Felipe Braule",
};
const atletico = {
  id: "16",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/12/7980.png",
  nome: "Atlético de Madrid",
  treinador: "Maicon",
};
const milan = {
  id: "17",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/17/113.png",
  nome: "Milan",
  treinador: "Surprise",
};
const nassr = {
  id: "18",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/10/2506.png",
  nome: "Time do Talisca",
  treinador: "Allanzinn",
};

//daqui pra baixo API testes
const camp = [
  {
    id: "1",
    name: "Premier League",
    table: [
      {
        posicao: 1,
        equipe: chelsea,
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: "0",
        forma: [],
      },
      {
        posicao: 2,
        equipe: realMadrid,
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: "0",
        forma: [],
      },
      {
        posicao: 3,
        equipe: manchesterCity,
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: "0",
        forma: [],
      },
      {
        posicao: 4,
        equipe: juventus,
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: "0",
        forma: [],
      },
      {
        posicao: 5,
        equipe: psg,
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: "0",
        forma: [],
      },
      {
        posicao: 6,
        equipe: barcelona,
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: "0",
        forma: [],
      },
      {
        posicao: 7,
        equipe: bayern,
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: "0",
        forma: [],
      },
      {
        posicao: 8,
        equipe: liverpool,
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: "0",
        forma: [],
      },
      {
        posicao: 9,
        equipe: tottenham,
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: "0",
        forma: [],
      },
      {
        posicao: 10,
        equipe: manchesterUnited,
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: "0",
        forma: [],
      },
      {
        posicao: 11,
        equipe: inter,
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: "0",
        forma: [],
      },
      {
        posicao: 12,
        equipe: arsenal,
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: "0",
        forma: [],
      },
      {
        posicao: 13,
        equipe: leipzig,
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: "0",
        forma: [],
      },
      {
        posicao: 14,
        equipe: dortmund,
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: "0",
        forma: [],
      },
      {
        posicao: 15,
        equipe: marseille,
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: "0",
        forma: [],
      },
      {
        posicao: 16,
        equipe: atletico,
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: "0",
        forma: [],
      },
      {
        posicao: 17,
        equipe: milan,
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: "0",
        forma: [],
      },
      {
        posicao: 18,
        equipe: nassr,
        pontos: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: "0",
        forma: [],
      },
    ],
  },
];

const rodada1 = [
  {
    idCampeonato: "1",
    idPartida: "1000",
    casa: chelsea,
    fora: tottenham,
    rodada: "1",
    status: "MARCADO",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1001",
    casa: inter,
    fora: dortmund,
    rodada: "1",
    status: "MARCADO",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1002",
    casa: realMadrid,
    fora: juventus,
    rodada: "1",
    status: "MARCADO",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1003",
    casa: marseille,
    fora: manchesterCity,
    rodada: "1",
    status: "MARCADO",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1004",
    casa: manchesterUnited,
    fora: bayern,
    rodada: "1",
    status: "MARCADO",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1005",
    casa: nassr,
    fora: liverpool,
    rodada: "1",
    status: "MARCADO",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1006",
    casa: arsenal,
    fora: leipzig,
    rodada: "1",
    status: "MARCADO",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1007",
    casa: psg,
    fora: atletico,
    rodada: "1",
    status: "MARCADO",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1008",
    casa: milan,
    fora: barcelona,
    rodada: "1",
    status: "MARCADO",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada2 = [
  {
    idCampeonato: "1",
    idPartida: "1010",
    casa: chelsea,
    fora: dortmund,
    rodada: "2",
    status: "MARCADO",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1011",
    casa: tottenham,
    fora: juventus,
    rodada: "2",
    status: "MARCADO",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1012",
    casa: inter,
    fora: manchesterCity,
    rodada: "2",
    status: "MARCADO",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1013",
    casa: realMadrid,
    fora: bayern,
    rodada: "2",
    status: "MARCADO",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1014",
    casa: marseille,
    fora: liverpool,
    rodada: "2",
    status: "MARCADO",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1015",
    casa: manchesterUnited,
    fora: leipzig,
    rodada: "2",
    status: "MARCADO",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1016",
    casa: nassr,
    fora: atletico,
    rodada: "2",
    status: "MARCADO",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1017",
    casa: arsenal,
    fora: barcelona,
    rodada: "2",
    status: "MARCADO",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1018",
    casa: psg,
    fora: milan,
    rodada: "2",
    status: "MARCADO",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodadas = [
  { num: "1", rodada: rodada1 },
  { num: "2", rodada: rodada2 },
];

const equipes = [
  chelsea,
  realMadrid,
  manchesterCity,
  juventus,
  psg,
  barcelona,
  bayern,
  liverpool,
  tottenham,
  manchesterUnited,
  inter,
  arsenal,
  leipzig,
  dortmund,
  marseille,
  atletico,
  milan,
  nassr,
];

app.get("/camp", (req, res) => {
  res.json({ camp });
});

app.get("/rodadas", (req, res) => {
  res.json({ rodadas });
});

app.get("/equipes", (req, res) => {
  res.json({ equipes });
});

export default app;
