import express from "express";
import cors from "cors";

const app = express();
app.use(cors());
app.use(express.json());

//app.use("/api/v1/football", football);
//app.use("*", (req, res) => res.status(404).json({ error: "not found" }));

const chelsea = {
  id: "1",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/18/18.png",
  nome: "Chelsea",
  treinador: "Delsin",
};
const realMadrid = {
  id: "2",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/12/3468.png",
  nome: "Real Madrid",
  treinador: "Danikro",
};
const manchesterCity = {
  id: "3",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/9/9.png",
  nome: "Manchester City",
  treinador: "Lil Dani",
};
const juventus = {
  id: "4",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/2/10850.png",
  nome: "Juventus",
  treinador: "Edu",
};
const psg = {
  id: "5",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/15/591.png",
  nome: "Paris Saint Germain",
  treinador: "Borraxa Diniz",
};
const barcelona = {
  id: "6",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/19/83.png",
  nome: "Barcelona",
  treinador: "Rafi Hernandez",
};
const bayern = {
  id: "7",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/23/503.png",
  nome: "Bayern Munchen",
  treinador: "PH",
};
const liverpool = {
  id: "8",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/8/8.png",
  nome: "Liverpool",
  treinador: "Klopp LaminaZ",
};
const tottenham = {
  id: "9",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/6/6.png",
  nome: "Tottenham",
  treinador: "Crazzy",
};
const manchesterUnited = {
  id: "10",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/14/14.png",
  nome: "Manchester United",
  treinador: "Baitzera",
};
const inter = {
  id: "11",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/18/2930.png",
  nome: "Inter",
  treinador: "Vaga",
};
const arsenal = {
  id: "12",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/19/19.png",
  nome: "Arsenal",
  treinador: "Renan",
};
const leipzig = {
  id: "13",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/21/277.png",
  nome: "RB Leipzig",
  treinador: "Erick",
};
const dortmund = {
  id: "14",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/4/68.png",
  nome: "Borussia Dortmund",
  treinador: "Felipe Braule",
};
const atletico = {
  id: "15",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/12/7980.png",
  nome: "Atlético de Madrid",
  treinador: "Maicon",
};
const milan = {
  id: "16",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/17/113.png",
  nome: "Milan",
  treinador: "Surprise",
};
const nassr = {
  id: "17",
  logo: "https://cdn.sportmonks.com/images/soccer/teams/10/2506.png",
  nome: "Time do Talisca",
  treinador: "Allanzinn",
};
const bye = {
  id: "18",
  logo: "",
  nome: "BYE",
  treinador: "",
};

//daqui pra baixo API testes
const camp = [
  {
    id: "1",
    name: "CDRZAO",
    table: [
      {
        posicao: 1,
        equipe: chelsea,
        pontos: 0,
        partidas: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: 0,
        forma: [],
      },
      {
        posicao: 2,
        equipe: realMadrid,
        pontos: 0,
        partidas: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: 0,
        forma: [],
      },
      {
        posicao: 3,
        equipe: manchesterCity,
        pontos: 0,
        partidas: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: 0,
        forma: [],
      },
      {
        posicao: 4,
        equipe: juventus,
        pontos: 0,
        partidas: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: 0,
        forma: [],
      },
      {
        posicao: 5,
        equipe: psg,
        pontos: 0,
        partidas: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: 0,
        forma: [],
      },
      {
        posicao: 6,
        equipe: barcelona,
        pontos: 0,
        partidas: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: 0,
        forma: [],
      },
      {
        posicao: 7,
        equipe: bayern,
        pontos: 0,
        partidas: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: 0,
        forma: [],
      },
      {
        posicao: 8,
        equipe: liverpool,
        pontos: 0,
        partidas: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: 0,
        forma: [],
      },
      {
        posicao: 9,
        equipe: tottenham,
        pontos: 0,
        partidas: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: 0,
        forma: [],
      },
      {
        posicao: 10,
        equipe: manchesterUnited,
        pontos: 0,
        partidas: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: 0,
        forma: [],
      },
      {
        posicao: 11,
        equipe: inter,
        pontos: 0,
        partidas: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: 0,
        forma: [],
      },
      {
        posicao: 12,
        equipe: arsenal,
        pontos: 0,
        partidas: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: 0,
        forma: [],
      },
      {
        posicao: 13,
        equipe: leipzig,
        pontos: 0,
        partidas: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: 0,
        forma: [],
      },
      {
        posicao: 14,
        equipe: dortmund,
        pontos: 0,
        partidas: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: 0,
        forma: [],
      },
      {
        posicao: 15,
        equipe: atletico,
        pontos: 0,
        partidas: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: 0,
        forma: [],
      },
      {
        posicao: 16,
        equipe: milan,
        pontos: 0,
        partidas: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: 0,
        forma: [],
      },
      {
        posicao: 17,
        equipe: nassr,
        pontos: 0,
        partidas: 0,
        vitorias: 0,
        empates: 0,
        derrotas: 0,
        gols_marcados: 0,
        gols_sofridos: 0,
        saldo_de_gols: 0,
        aproveitamento: 0,
        forma: [],
      },
    ],
  },
];

const rodada1 = [
  {
    idCampeonato: "1",
    idPartida: "1000",
    casa: chelsea,
    fora: tottenham,
    status: "REALIZADO",
    data: "2023-03-02T17:53:04.454Z",
    placarCasa: "1",
    placarFora: "3",
  },
  {
    idCampeonato: "1",
    idPartida: "1001",
    casa: inter,
    fora: dortmund,
    status: "REALIZADO",
    data: "2023-03-02T15:46:48.934Z",
    placarCasa: "5",
    placarFora: "2",
  },
  {
    idCampeonato: "1",
    idPartida: "1002",
    casa: realMadrid,
    fora: juventus,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1003",
    casa: bye,
    fora: manchesterCity,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1004",
    casa: manchesterUnited,
    fora: bayern,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1005",
    casa: nassr,
    fora: liverpool,
    status: "REALIZADO",
    data: "2023-03-01T19:32:02.778Z",
    placarCasa: "0",
    placarFora: "5",
  },
  {
    idCampeonato: "1",
    idPartida: "1006",
    casa: leipzig,
    fora: arsenal,
    status: "REALIZADO",
    data: "2023-03-02T17:54:01.540Z",
    placarCasa: "12",
    placarFora: "1",
  },
  {
    idCampeonato: "1",
    idPartida: "1007",
    casa: psg,
    fora: atletico,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1008",
    casa: milan,
    fora: barcelona,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada2 = [
  {
    idCampeonato: "1",
    idPartida: "1010",
    casa: dortmund,
    fora: chelsea,
    status: "REALIZADO",
    data: "2023-03-04T19:40:14.161Z",
    placarCasa: "0",
    placarFora: "5",
  },
  {
    idCampeonato: "1",
    idPartida: "1011",
    casa: tottenham,
    fora: juventus,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1012",
    casa: manchesterCity,
    fora: inter,
    status: "REALIZADO",
    data: "2023-03-02T17:38:59.410Z",
    placarCasa: "2",
    placarFora: "2",
  },
  {
    idCampeonato: "1",
    idPartida: "1013",
    casa: realMadrid,
    fora: bayern,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1014",
    casa: bye,
    fora: liverpool,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1015",
    casa: leipzig,
    fora: manchesterUnited,
    status: "REALIZADO",
    data: "2023-03-04T20:59:58.588Z",
    placarCasa: "5",
    placarFora: "2",
  },
  {
    idCampeonato: "1",
    idPartida: "1016",
    casa: nassr,
    fora: atletico,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1017",
    casa: arsenal,
    fora: barcelona,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1018",
    casa: psg,
    fora: milan,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada3 = [
  {
    idCampeonato: "1",
    idPartida: "1020",
    casa: chelsea,
    fora: juventus,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1021",
    casa: dortmund,
    fora: manchesterCity,
    status: "REALIZADO",
    data: "2023-03-02T17:41:56.282Z",
    placarCasa: "2",
    placarFora: "1",
  },
  {
    idCampeonato: "1",
    idPartida: "1022",
    casa: tottenham,
    fora: bayern,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1023",
    casa: liverpool,
    fora: inter,
    status: "REALIZADO",
    data: "2023-03-04T21:18:50.539Z",
    placarCasa: "4",
    placarFora: "3",
  },
  {
    idCampeonato: "1",
    idPartida: "1024",
    casa: realMadrid,
    fora: leipzig,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1025",
    casa: bye,
    fora: atletico,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1026",
    casa: manchesterUnited,
    fora: barcelona,
    status: "REALIZADO",
    data: "2023-03-04T21:15:11.588Z",
    placarCasa: "4",
    placarFora: "4",
  },
  {
    idCampeonato: "1",
    idPartida: "1027",
    casa: nassr,
    fora: milan,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1028",
    casa: arsenal,
    fora: psg,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada4 = [
  {
    idCampeonato: "1",
    idPartida: "1030",
    casa: manchesterCity,
    fora: chelsea,
    status: "REALIZADO",
    data: "2023-03-04T21:08:59.045Z",
    placarCasa: "4",
    placarFora: "2",
  },
  {
    idCampeonato: "1",
    idPartida: "1031",
    casa: juventus,
    fora: bayern,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1032",
    casa: dortmund,
    fora: liverpool,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1033",
    casa: leipzig,
    fora: tottenham,
    status: "REALIZADO",
    data: "2023-03-02T17:44:22.165Z",
    placarCasa: "1",
    placarFora: "4",
  },
  {
    idCampeonato: "1",
    idPartida: "1034",
    casa: inter,
    fora: atletico,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1035",
    casa: realMadrid,
    fora: barcelona,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1036",
    casa: bye,
    fora: milan,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1037",
    casa: manchesterUnited,
    fora: psg,
    status: "REALIZADO",
    data: "2023-03-04T20:52:34.280Z",
    placarCasa: "4",
    placarFora: "3",
  },
  {
    idCampeonato: "1",
    idPartida: "1038",
    casa: nassr,
    fora: arsenal,
    status: "REALIZADO",
    data: "2023-03-02T17:37:30.798Z",
    placarCasa: "0",
    placarFora: "3",
  },
];

const rodada5 = [
  {
    idCampeonato: "1",
    idPartida: "1040",
    casa: chelsea,
    fora: bayern,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1041",
    casa: manchesterCity,
    fora: liverpool,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1042",
    casa: juventus,
    fora: leipzig,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1043",
    casa: dortmund,
    fora: atletico,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1044",
    casa: tottenham,
    fora: barcelona,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1045",
    casa: inter,
    fora: milan,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1046",
    casa: realMadrid,
    fora: psg,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1047",
    casa: bye,
    fora: arsenal,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1048",
    casa: manchesterUnited,
    fora: nassr,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada6 = [
  {
    idCampeonato: "1",
    idPartida: "1050",
    casa: liverpool,
    fora: chelsea,
    status: "REALIZADO",
    data: "2023-03-04T19:34:10.863Z",
    placarCasa: "1",
    placarFora: "1",
  },
  {
    idCampeonato: "1",
    idPartida: "1051",
    casa: leipzig,
    fora: bayern,
    status: "REALIZADO",
    data: "2023-03-04T20:53:39.118Z",
    placarCasa: "8",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1052",
    casa: manchesterCity,
    fora: atletico,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1053",
    casa: juventus,
    fora: barcelona,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1054",
    casa: dortmund,
    fora: milan,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1055",
    casa: tottenham,
    fora: psg,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1056",
    casa: inter,
    fora: arsenal,
    status: "REALIZADO",
    data: "2023-03-02T15:58:52.904Z",
    placarCasa: "4",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1057",
    casa: realMadrid,
    fora: nassr,
    status: "REALIZADO",
    data: "2023-03-02T15:46:48.934Z",
    placarCasa: "3",
    placarFora: "4",
  },
  {
    idCampeonato: "1",
    idPartida: "1058",
    casa: bye,
    fora: manchesterUnited,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada7 = [
  {
    idCampeonato: "1",
    idPartida: "1060",
    casa: leipzig,
    fora: chelsea,
    status: "REALIZADO",
    data: "2023-03-03T13:58:05.678Z",
    placarCasa: "3",
    placarFora: "2",
  },
  {
    idCampeonato: "1",
    idPartida: "1061",
    casa: liverpool,
    fora: atletico,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1062",
    casa: bayern,
    fora: barcelona,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1063",
    casa: manchesterCity,
    fora: milan,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1064",
    casa: juventus,
    fora: psg,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1065",
    casa: dortmund,
    fora: arsenal,
    status: "REALIZADO",
    data: "2023-03-02T16:01:00.721Z",
    placarCasa: "6",
    placarFora: "2",
  },
  {
    idCampeonato: "1",
    idPartida: "1066",
    casa: tottenham,
    fora: nassr,
    status: "REALIZADO",
    data: "2023-03-02T17:46:32.789Z",
    placarCasa: "10",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1067",
    casa: inter,
    fora: manchesterUnited,
    status: "REALIZADO",
    data: "2023-03-04T21:12:42.831Z",
    placarCasa: "1",
    placarFora: "2",
  },
  {
    idCampeonato: "1",
    idPartida: "1068",
    casa: realMadrid,
    fora: bye,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada8 = [
  {
    idCampeonato: "1",
    idPartida: "1070",
    casa: chelsea,
    fora: atletico,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1071",
    casa: leipzig,
    fora: barcelona,
    status: "REALIZADO",
    data: "2023-03-03T13:56:28.437Z",
    placarCasa: "2",
    placarFora: "4",
  },
  {
    idCampeonato: "1",
    idPartida: "1072",
    casa: liverpool,
    fora: milan,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1073",
    casa: bayern,
    fora: psg,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1074",
    casa: manchesterCity,
    fora: arsenal,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1075",
    casa: juventus,
    fora: nassr,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1076",
    casa: manchesterUnited,
    fora: dortmund,
    status: "REALIZADO",
    data: "2023-03-04T21:10:43.077Z",
    placarCasa: "7",
    placarFora: "1",
  },
  {
    idCampeonato: "1",
    idPartida: "1077",
    casa: tottenham,
    fora: bye,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1078",
    casa: realMadrid,
    fora: inter,
    status: "REALIZADO",
    data: "2023-03-02T15:52:56.584Z",
    placarCasa: "4",
    placarFora: "3",
  },
];

const rodada9 = [
  {
    idCampeonato: "1",
    idPartida: "1080",
    casa: chelsea,
    fora: barcelona,
    status: "REALIZADO",
    data: "2023-03-03T13:57:42.299Z",
    placarCasa: "1",
    placarFora: "5",
  },
  {
    idCampeonato: "1",
    idPartida: "1081",
    casa: atletico,
    fora: milan,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1082",
    casa: psg,
    fora: leipzig,
    status: "REALIZADO",
    data: "2023-03-02T17:38:59.410Z",
    placarCasa: "3",
    placarFora: "5",
  },
  {
    idCampeonato: "1",
    idPartida: "1083",
    casa: liverpool,
    fora: arsenal,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1084",
    casa: bayern,
    fora: nassr,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1085",
    casa: manchesterCity,
    fora: manchesterUnited,
    status: "REALIZADO",
    data: "2023-03-04T20:57:52.653Z",
    placarCasa: "2",
    placarFora: "3",
  },
  {
    idCampeonato: "1",
    idPartida: "1086",
    casa: juventus,
    fora: bye,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1087",
    casa: dortmund,
    fora: realMadrid,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1088",
    casa: tottenham,
    fora: inter,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada10 = [
  {
    idCampeonato: "1",
    idPartida: "1090",
    casa: chelsea,
    fora: milan,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1091",
    casa: psg,
    fora: barcelona,
    status: "REALIZADO",
    data: "2023-03-04T21:11:17.752Z",
    placarCasa: "9",
    placarFora: "1",
  },
  {
    idCampeonato: "1",
    idPartida: "1092",
    casa: atletico,
    fora: arsenal,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1093",
    casa: leipzig,
    fora: nassr,
    status: "REALIZADO",
    data: "2023-03-02T17:50:44.239Z",
    placarCasa: "4",
    placarFora: "3",
  },
  {
    idCampeonato: "1",
    idPartida: "1094",
    casa: liverpool,
    fora: manchesterUnited,
    status: "REALIZADO",
    data: "2023-03-04T21:20:00.567Z",
    placarCasa: "2",
    placarFora: "3",
  },
  {
    idCampeonato: "1",
    idPartida: "1095",
    casa: bayern,
    fora: bye,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1096",
    casa: manchesterCity,
    fora: realMadrid,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1097",
    casa: juventus,
    fora: inter,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1098",
    casa: dortmund,
    fora: tottenham,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada11 = [
  {
    idCampeonato: "1",
    idPartida: "1100",
    casa: psg,
    fora: chelsea,
    status: "REALIZADO",
    data: "2023-03-04T21:13:49.881Z",
    placarCasa: "1",
    placarFora: "3",
  },
  {
    idCampeonato: "1",
    idPartida: "1101",
    casa: milan,
    fora: arsenal,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1102",
    casa: nassr,
    fora: barcelona,
    status: "REALIZADO",
    data: "2023-03-03T13:55:58.305Z",
    placarCasa: "0",
    placarFora: "5",
  },
  {
    idCampeonato: "1",
    idPartida: "1103",
    casa: atletico,
    fora: manchesterUnited,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1104",
    casa: leipzig,
    fora: bye,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1105",
    casa: liverpool,
    fora: realMadrid,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1106",
    casa: bayern,
    fora: inter,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1107",
    casa: manchesterCity,
    fora: tottenham,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1108",
    casa: juventus,
    fora: dortmund,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada12 = [
  {
    idCampeonato: "1",
    idPartida: "1110",
    casa: chelsea,
    fora: arsenal,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1111",
    casa: psg,
    fora: nassr,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1112",
    casa: milan,
    fora: manchesterUnited,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1113",
    casa: barcelona,
    fora: bye,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1114",
    casa: atletico,
    fora: realMadrid,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1115",
    casa: leipzig,
    fora: inter,
    status: "REALIZADO",
    data: "2023-03-02T17:49:12.030Z",
    placarCasa: "2",
    placarFora: "2",
  },
  {
    idCampeonato: "1",
    idPartida: "1116",
    casa: liverpool,
    fora: tottenham,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1117",
    casa: bayern,
    fora: dortmund,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1118",
    casa: manchesterCity,
    fora: juventus,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada13 = [
  {
    idCampeonato: "1",
    idPartida: "1120",
    casa: chelsea,
    fora: nassr,
    status: "REALIZADO",
    data: "2023-03-02T17:51:43.103Z",
    placarCasa: "10",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1121",
    casa: arsenal,
    fora: manchesterUnited,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1122",
    casa: psg,
    fora: bye,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1123",
    casa: milan,
    fora: realMadrid,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1124",
    casa: inter,
    fora: barcelona,
    status: "REALIZADO",
    data: "2023-03-04T21:19:28.492Z",
    placarCasa: "1",
    placarFora: "4",
  },
  {
    idCampeonato: "1",
    idPartida: "1125",
    casa: atletico,
    fora: tottenham,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1126",
    casa: leipzig,
    fora: dortmund,
    status: "REALIZADO",
    data: "2023-03-02T17:42:03.259Z",
    placarCasa: "6",
    placarFora: "2",
  },
  {
    idCampeonato: "1",
    idPartida: "1127",
    casa: liverpool,
    fora: juventus,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1128",
    casa: bayern,
    fora: manchesterCity,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada14 = [
  {
    idCampeonato: "1",
    idPartida: "1130",
    casa: chelsea,
    fora: manchesterUnited,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1131",
    casa: nassr,
    fora: bye,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1132",
    casa: arsenal,
    fora: realMadrid,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1133",
    casa: psg,
    fora: inter,
    status: "REALIZADO",
    data: "2023-03-02T17:45:15.462Z",
    placarCasa: "3",
    placarFora: "4",
  },
  {
    idCampeonato: "1",
    idPartida: "1134",
    casa: milan,
    fora: tottenham,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1135",
    casa: dortmund,
    fora: barcelona,
    status: "REALIZADO",
    data: "2023-03-04T20:53:02.432Z",
    placarCasa: "3",
    placarFora: "8",
  },
  {
    idCampeonato: "1",
    idPartida: "1136",
    casa: atletico,
    fora: juventus,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1137",
    casa: manchesterCity,
    fora: leipzig,
    status: "REALIZADO",
    data: "2023-03-04T19:39:29.275Z",
    placarCasa: "3",
    placarFora: "1",
  },
  {
    idCampeonato: "1",
    idPartida: "1138",
    casa: liverpool,
    fora: bayern,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada15 = [
  {
    idCampeonato: "1",
    idPartida: "1140",
    casa: chelsea,
    fora: bye,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1141",
    casa: manchesterUnited,
    fora: realMadrid,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1142",
    casa: nassr,
    fora: inter,
    status: "REALIZADO",
    data: "2023-03-02T17:36:51.178Z",
    placarCasa: "1",
    placarFora: "6",
  },
  {
    idCampeonato: "1",
    idPartida: "1143",
    casa: arsenal,
    fora: tottenham,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1144",
    casa: psg,
    fora: dortmund,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1145",
    casa: milan,
    fora: juventus,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1146",
    casa: barcelona,
    fora: manchesterCity,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1147",
    casa: atletico,
    fora: bayern,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1148",
    casa: leipzig,
    fora: liverpool,
    status: "REALIZADO",
    data: "2023-03-04T21:11:49.468Z",
    placarCasa: "2",
    placarFora: "3",
  },
];

const rodada16 = [
  {
    idCampeonato: "1",
    idPartida: "1150",
    casa: chelsea,
    fora: realMadrid,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1151",
    casa: bye,
    fora: inter,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1152",
    casa: manchesterUnited,
    fora: tottenham,
    status: "REALIZADO",
    data: "2023-03-04T19:34:24.199Z",
    placarCasa: "2",
    placarFora: "1",
  },
  {
    idCampeonato: "1",
    idPartida: "1153",
    casa: nassr,
    fora: dortmund,
    status: "REALIZADO",
    data: "2023-03-02T15:52:56.584Z",
    placarCasa: "2",
    placarFora: "10",
  },
  {
    idCampeonato: "1",
    idPartida: "1154",
    casa: arsenal,
    fora: juventus,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1155",
    casa: manchesterCity,
    fora: psg,
    status: "REALIZADO",
    data: "2023-03-02T17:43:19.333Z",
    placarCasa: "6",
    placarFora: "1",
  },
  {
    idCampeonato: "1",
    idPartida: "1156",
    casa: milan,
    fora: bayern,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1157",
    casa: barcelona,
    fora: liverpool,
    status: "REALIZADO",
    data: "2023-03-04T21:09:04.753Z",
    placarCasa: "2",
    placarFora: "3",
  },
  {
    idCampeonato: "1",
    idPartida: "1158",
    casa: atletico,
    fora: leipzig,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada17 = [
  {
    idCampeonato: "1",
    idPartida: "1160",
    casa: inter,
    fora: chelsea,
    status: "REALIZADO",
    data: "2023-03-04T21:10:51.471Z",
    placarCasa: "4",
    placarFora: "1",
  },
  {
    idCampeonato: "1",
    idPartida: "1161",
    casa: realMadrid,
    fora: tottenham,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1162",
    casa: bye,
    fora: dortmund,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1163",
    casa: manchesterUnited,
    fora: juventus,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1164",
    casa: nassr,
    fora: manchesterCity,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1165",
    casa: arsenal,
    fora: bayern,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1166",
    casa: psg,
    fora: liverpool,
    status: "REALIZADO",
    data: "2023-03-04T20:57:57.717Z",
    placarCasa: "5",
    placarFora: "4",
  },
  {
    idCampeonato: "1",
    idPartida: "1167",
    casa: milan,
    fora: leipzig,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1168",
    casa: barcelona,
    fora: atletico,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada18 = [
  {
    idCampeonato: "1",
    idPartida: "1170",
    casa: tottenham,
    fora: chelsea,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1171",
    casa: dortmund,
    fora: inter,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1172",
    casa: realMadrid,
    fora: juventus,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1173",
    casa: bye,
    fora: manchesterCity,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1174",
    casa: manchesterUnited,
    fora: bayern,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1175",
    casa: liverpool,
    fora: nassr,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1176",
    casa: arsenal,
    fora: leipzig,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1177",
    casa: psg,
    fora: atletico,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1178",
    casa: milan,
    fora: barcelona,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada19 = [
  {
    idCampeonato: "1",
    idPartida: "1180",
    casa: chelsea,
    fora: dortmund,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1181",
    casa: tottenham,
    fora: juventus,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1182",
    casa: inter,
    fora: manchesterCity,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1183",
    casa: realMadrid,
    fora: bayern,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1184",
    casa: bye,
    fora: liverpool,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1185",
    casa: manchesterUnited,
    fora: leipzig,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1186",
    casa: nassr,
    fora: atletico,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1187",
    casa: arsenal,
    fora: barcelona,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1188",
    casa: psg,
    fora: milan,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada20 = [
  {
    idCampeonato: "1",
    idPartida: "1190",
    casa: chelsea,
    fora: juventus,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1191",
    casa: manchesterCity,
    fora: dortmund,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1192",
    casa: tottenham,
    fora: bayern,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1193",
    casa: inter,
    fora: liverpool,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1194",
    casa: realMadrid,
    fora: leipzig,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1195",
    casa: bye,
    fora: atletico,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1196",
    casa: barcelona,
    fora: manchesterUnited,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1197",
    casa: nassr,
    fora: milan,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1198",
    casa: arsenal,
    fora: psg,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada21 = [
  {
    idCampeonato: "1",
    idPartida: "1200",
    casa: chelsea,
    fora: manchesterCity,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1201",
    casa: juventus,
    fora: bayern,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1202",
    casa: dortmund,
    fora: liverpool,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1203",
    casa: tottenham,
    fora: leipzig,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1204",
    casa: inter,
    fora: atletico,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1205",
    casa: realMadrid,
    fora: barcelona,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1206",
    casa: bye,
    fora: milan,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1207",
    casa: psg,
    fora: manchesterUnited,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1208",
    casa: arsenal,
    fora: nassr,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada22 = [
  {
    idCampeonato: "1",
    idPartida: "1210",
    casa: chelsea,
    fora: bayern,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1211",
    casa: manchesterCity,
    fora: liverpool,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1212",
    casa: juventus,
    fora: leipzig,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1213",
    casa: dortmund,
    fora: atletico,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1214",
    casa: tottenham,
    fora: barcelona,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1215",
    casa: inter,
    fora: milan,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1216",
    casa: realMadrid,
    fora: psg,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1217",
    casa: bye,
    fora: arsenal,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1218",
    casa: manchesterUnited,
    fora: nassr,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada23 = [
  {
    idCampeonato: "1",
    idPartida: "1220",
    casa: chelsea,
    fora: liverpool,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1221",
    casa: bayern,
    fora: leipzig,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1222",
    casa: manchesterCity,
    fora: atletico,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1223",
    casa: juventus,
    fora: barcelona,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1224",
    casa: dortmund,
    fora: milan,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1225",
    casa: tottenham,
    fora: psg,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1226",
    casa: arsenal,
    fora: inter,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1227",
    casa: nassr,
    fora: realMadrid,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1228",
    casa: bye,
    fora: manchesterUnited,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada24 = [
  {
    idCampeonato: "1",
    idPartida: "1230",
    casa: chelsea,
    fora: leipzig,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1231",
    casa: liverpool,
    fora: atletico,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1232",
    casa: bayern,
    fora: barcelona,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1233",
    casa: manchesterCity,
    fora: milan,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1234",
    casa: juventus,
    fora: psg,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1235",
    casa: arsenal,
    fora: dortmund,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1236",
    casa: nassr,
    fora: tottenham,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1237",
    casa: manchesterUnited,
    fora: inter,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1238",
    casa: realMadrid,
    fora: bye,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada25 = [
  {
    idCampeonato: "1",
    idPartida: "1240",
    casa: chelsea,
    fora: atletico,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1241",
    casa: barcelona,
    fora: leipzig,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1242",
    casa: liverpool,
    fora: milan,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1243",
    casa: bayern,
    fora: psg,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1244",
    casa: manchesterCity,
    fora: arsenal,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1245",
    casa: juventus,
    fora: nassr,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1246",
    casa: dortmund,
    fora: manchesterUnited,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1247",
    casa: tottenham,
    fora: bye,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1248",
    casa: inter,
    fora: realMadrid,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada26 = [
  {
    idCampeonato: "1",
    idPartida: "1250",
    casa: barcelona,
    fora: chelsea,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1251",
    casa: atletico,
    fora: milan,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1252",
    casa: leipzig,
    fora: psg,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1253",
    casa: liverpool,
    fora: arsenal,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1254",
    casa: bayern,
    fora: nassr,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1255",
    casa: manchesterUnited,
    fora: manchesterCity,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1256",
    casa: juventus,
    fora: bye,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1257",
    casa: dortmund,
    fora: realMadrid,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1258",
    casa: tottenham,
    fora: inter,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada27 = [
  {
    idCampeonato: "1",
    idPartida: "1260",
    casa: chelsea,
    fora: milan,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1261",
    casa: barcelona,
    fora: psg,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1262",
    casa: atletico,
    fora: arsenal,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1263",
    casa: nassr,
    fora: leipzig,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1264",
    casa: manchesterUnited,
    fora: liverpool,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1265",
    casa: bayern,
    fora: bye,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1266",
    casa: manchesterCity,
    fora: realMadrid,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1267",
    casa: juventus,
    fora: inter,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1268",
    casa: dortmund,
    fora: tottenham,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada28 = [
  {
    idCampeonato: "1",
    idPartida: "1270",
    casa: chelsea,
    fora: psg,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1271",
    casa: milan,
    fora: arsenal,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1272",
    casa: barcelona,
    fora: nassr,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1273",
    casa: atletico,
    fora: manchesterUnited,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1274",
    casa: leipzig,
    fora: bye,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1275",
    casa: liverpool,
    fora: realMadrid,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1276",
    casa: bayern,
    fora: inter,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1277",
    casa: manchesterCity,
    fora: tottenham,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1278",
    casa: juventus,
    fora: dortmund,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada29 = [
  {
    idCampeonato: "1",
    idPartida: "1280",
    casa: chelsea,
    fora: arsenal,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1281",
    casa: psg,
    fora: nassr,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1282",
    casa: milan,
    fora: manchesterUnited,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1283",
    casa: barcelona,
    fora: bye,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1284",
    casa: atletico,
    fora: realMadrid,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1285",
    casa: inter,
    fora: leipzig,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1286",
    casa: liverpool,
    fora: tottenham,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1287",
    casa: bayern,
    fora: dortmund,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1288",
    casa: manchesterCity,
    fora: juventus,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada30 = [
  {
    idCampeonato: "1",
    idPartida: "1290",
    casa: nassr,
    fora: chelsea,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1291",
    casa: arsenal,
    fora: manchesterUnited,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1292",
    casa: psg,
    fora: bye,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1293",
    casa: milan,
    fora: realMadrid,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1294",
    casa: barcelona,
    fora: inter,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1295",
    casa: atletico,
    fora: tottenham,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1296",
    casa: dortmund,
    fora: leipzig,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1297",
    casa: liverpool,
    fora: juventus,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1298",
    casa: bayern,
    fora: manchesterCity,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada31 = [
  {
    idCampeonato: "1",
    idPartida: "1300",
    casa: chelsea,
    fora: manchesterUnited,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1301",
    casa: nassr,
    fora: bye,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1302",
    casa: arsenal,
    fora: realMadrid,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1303",
    casa: inter,
    fora: psg,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1304",
    casa: milan,
    fora: tottenham,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1305",
    casa: barcelona,
    fora: dortmund,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1306",
    casa: atletico,
    fora: juventus,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1307",
    casa: leipzig,
    fora: manchesterCity,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1308",
    casa: liverpool,
    fora: bayern,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada32 = [
  {
    idCampeonato: "1",
    idPartida: "1310",
    casa: chelsea,
    fora: bye,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1311",
    casa: manchesterUnited,
    fora: realMadrid,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1312",
    casa: inter,
    fora: nassr,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1313",
    casa: arsenal,
    fora: tottenham,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1314",
    casa: psg,
    fora: dortmund,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1315",
    casa: milan,
    fora: juventus,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1316",
    casa: barcelona,
    fora: manchesterCity,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1317",
    casa: atletico,
    fora: bayern,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1318",
    casa: liverpool,
    fora: leipzig,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada33 = [
  {
    idCampeonato: "1",
    idPartida: "1320",
    casa: chelsea,
    fora: realMadrid,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1321",
    casa: bye,
    fora: inter,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1322",
    casa: tottenham,
    fora: manchesterUnited,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1323",
    casa: dortmund,
    fora: nassr,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1324",
    casa: arsenal,
    fora: juventus,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1325",
    casa: psg,
    fora: manchesterCity,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1326",
    casa: milan,
    fora: bayern,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1327",
    casa: liverpool,
    fora: barcelona,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1328",
    casa: atletico,
    fora: leipzig,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodada34 = [
  {
    idCampeonato: "1",
    idPartida: "1330",
    casa: chelsea,
    fora: inter,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1331",
    casa: realMadrid,
    fora: tottenham,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1332",
    casa: bye,
    fora: dortmund,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1333",
    casa: manchesterUnited,
    fora: juventus,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1334",
    casa: nassr,
    fora: manchesterCity,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1335",
    casa: arsenal,
    fora: bayern,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1336",
    casa: liverpool,
    fora: psg,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1337",
    casa: milan,
    fora: leipzig,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
  {
    idCampeonato: "1",
    idPartida: "1338",
    casa: barcelona,
    fora: atletico,
    status: "MARCADO",
    data: "",
    placarCasa: "0",
    placarFora: "0",
  },
];

const rodadas = [
  { num: "1", rodada: rodada1 },
  { num: "2", rodada: rodada2 },
  { num: "3", rodada: rodada3 },
  { num: "4", rodada: rodada4 },
  { num: "5", rodada: rodada5 },
  { num: "6", rodada: rodada6 },
  { num: "7", rodada: rodada7 },
  { num: "8", rodada: rodada8 },
  { num: "9", rodada: rodada9 },
  { num: "10", rodada: rodada10 },
  { num: "11", rodada: rodada11 },
  { num: "12", rodada: rodada12 },
  { num: "13", rodada: rodada13 },
  { num: "14", rodada: rodada14 },
  { num: "15", rodada: rodada15 },
  { num: "16", rodada: rodada16 },
  { num: "17", rodada: rodada17 },
  { num: "18", rodada: rodada18 },
  { num: "19", rodada: rodada19 },
  { num: "20", rodada: rodada20 },
  { num: "21", rodada: rodada21 },
  { num: "22", rodada: rodada22 },
  { num: "23", rodada: rodada23 },
  { num: "24", rodada: rodada24 },
  { num: "25", rodada: rodada25 },
  { num: "26", rodada: rodada26 },
  { num: "27", rodada: rodada27 },
  { num: "28", rodada: rodada28 },
  { num: "29", rodada: rodada29 },
  { num: "30", rodada: rodada30 },
  { num: "31", rodada: rodada31 },
  { num: "32", rodada: rodada32 },
  { num: "33", rodada: rodada33 },
  { num: "34", rodada: rodada34 },
];

const equipes = [
  chelsea,
  realMadrid,
  manchesterCity,
  juventus,
  psg,
  barcelona,
  bayern,
  liverpool,
  tottenham,
  manchesterUnited,
  inter,
  arsenal,
  leipzig,
  dortmund,
  atletico,
  milan,
  nassr,
];

/* funcao para atualizar tabela */

equipes.forEach((equipe) => {
  let pontos = 0;
  let partidas = 0;
  let vitorias = 0;
  let empates = 0;
  let derrotas = 0;
  let gols_marcados = 0;
  let gols_sofridos = 0;
  let saldo_de_gols = 0;
  let aproveitamento = 0;

  for (let x = 0; x < rodadas.length; x++) {
    for (let y = 0; y < rodadas[x].rodada.length; y++) {
      if (
        rodadas[x].rodada[y].casa.nome === equipe.nome &&
        rodadas[x].rodada[y].status !== "MARCADO"
      ) {
        if (
          parseInt(rodadas[x].rodada[y].placarCasa) >
          parseInt(rodadas[x].rodada[y].placarFora)
        ) {
          pontos = pontos + 3;
          vitorias = vitorias + 1;
        } else if (
          parseInt(rodadas[x].rodada[y].placarCasa) ===
          parseInt(rodadas[x].rodada[y].placarFora)
        ) {
          pontos = pontos + 1;
          empates = empates + 1;
        } else {
          derrotas = derrotas + 1;
        }
        partidas = vitorias + empates + derrotas;
        gols_marcados =
          gols_marcados + parseInt(rodadas[x].rodada[y].placarCasa);
        gols_sofridos =
          gols_sofridos + parseInt(rodadas[x].rodada[y].placarFora);
        saldo_de_gols = gols_marcados - gols_sofridos;
        aproveitamento = parseFloat(pontos / (partidas * 3)).toFixed(2);
      } else if (
        rodadas[x].rodada[y].fora.nome === equipe.nome &&
        rodadas[x].rodada[y].status !== "MARCADO"
      ) {
        if (
          parseInt(rodadas[x].rodada[y].placarFora) >
          parseInt(rodadas[x].rodada[y].placarCasa)
        ) {
          pontos = pontos + 3;
          vitorias = vitorias + 1;
        } else if (
          parseInt(rodadas[x].rodada[y].placarFora) ===
          parseInt(rodadas[x].rodada[y].placarCasa)
        ) {
          pontos = pontos + 1;
          empates = empates + 1;
        } else {
          derrotas = derrotas + 1;
        }

        partidas = vitorias + empates + derrotas;
        gols_marcados =
          gols_marcados + parseInt(rodadas[x].rodada[y].placarFora);
        gols_sofridos =
          gols_sofridos + parseInt(rodadas[x].rodada[y].placarCasa);
        saldo_de_gols = gols_marcados - gols_sofridos;
        aproveitamento = parseFloat(pontos / (partidas * 3)).toFixed(2);
      }
    }
  }

  //arrumar for da forma
  let forma = ["", "", "", "", ""];
  let count = rodadas.length;
  let partida = "";
  for (let a = 0; a < rodadas.length; a++) {
    for (let b = 0; b < rodadas[a].rodada.length; b++) {
      if (
        (rodadas[a].rodada[b].casa.nome === equipe.nome ||
          rodadas[a].rodada[b].fora.nome === equipe.nome) &&
        rodadas[a].rodada[b].data !== ""
      ) {
        count = rodadas.length;
        for (let c = 0; c < rodadas.length; c++) {
          for (let d = 0; d < rodadas[c].rodada.length; d++) {
            if (
              (rodadas[c].rodada[d].casa.nome === equipe.nome ||
                rodadas[c].rodada[d].fora.nome === equipe.nome) &&
              rodadas[a].rodada[b].idPartida !==
                rodadas[c].rodada[d].idPartida &&
              (rodadas[c].rodada[d].data === "" ||
                new Date(rodadas[a].rodada[b].data) >
                  new Date(rodadas[c]?.rodada[d].data))
            ) {
            } else if (
              (rodadas[c].rodada[d].casa.nome === equipe.nome ||
                rodadas[c].rodada[d].fora.nome === equipe.nome) &&
              rodadas[a].rodada[b].idPartida !== rodadas[c].rodada[d].idPartida
            ) {
              count--;
            }
          }
        }

        if (rodadas[a].rodada[b].casa.nome === equipe.nome) {
          if (
            parseInt(rodadas[a].rodada[b].placarCasa) >
            parseInt(rodadas[a].rodada[b].placarFora)
          ) {
            partida = "V";
          } else if (
            parseInt(rodadas[a].rodada[b].placarCasa) ===
            parseInt(rodadas[a].rodada[b].placarFora)
          ) {
            partida = "E";
          } else {
            partida = "D";
          }
        } else if (rodadas[a].rodada[b].fora.nome === equipe.nome) {
          if (
            parseInt(rodadas[a].rodada[b].placarFora) >
            parseInt(rodadas[a].rodada[b].placarCasa)
          ) {
            partida = "V";
          } else if (
            parseInt(rodadas[a].rodada[b].placarFora) ===
            parseInt(rodadas[a].rodada[b].placarCasa)
          ) {
            partida = "E";
          } else {
            partida = "D";
          }
        }

        break;
      } else {
        count = 0;
      }
    }

    if (count === rodadas.length) {
      forma.splice(0, 1, partida);
    } else if (count === rodadas.length - 1) {
      forma.splice(1, 1, partida);
    } else if (count === rodadas.length - 2) {
      forma.splice(2, 1, partida);
    } else if (count === rodadas.length - 3) {
      forma.splice(3, 1, partida);
    } else if (count === rodadas.length - 4) {
      forma.splice(4, 1, partida);
    }
  }

  //posicao comparar equipe com o foreach abaixo

  for (let z = 0; z < camp[0].table.length; z++) {
    if (camp[0].table[z].equipe.nome === equipe.nome) {
      camp[0].table[z].pontos = pontos;
      camp[0].table[z].partidas = partidas;
      camp[0].table[z].vitorias = vitorias;
      camp[0].table[z].empates = empates;
      camp[0].table[z].derrotas = derrotas;
      camp[0].table[z].gols_marcados = gols_marcados;
      camp[0].table[z].gols_sofridos = gols_sofridos;
      camp[0].table[z].saldo_de_gols = saldo_de_gols;
      camp[0].table[z].aproveitamento = Math.trunc(aproveitamento * 100);
      camp[0].table[z].forma = forma;
      break;
    }
  }
});

equipes.forEach((equipe) => {
  for (let z = 0; z < camp[0].table.length; z++) {
    if (camp[0].table[z].equipe.nome === equipe.nome) {
      let posicao = 1;
      for (let z1 = 0; z1 < camp[0].table.length; z1++) {
        if (camp[0].table[z].equipe.nome != camp[0].table[z1].equipe.nome) {
          if (camp[0].table[z].pontos < camp[0].table[z1].pontos) {
            posicao++;
          } else if (camp[0].table[z].pontos === camp[0].table[z1].pontos) {
            if (
              camp[0].table[z].saldo_de_gols < camp[0].table[z1].saldo_de_gols
            ) {
              posicao++;
            } else if (
              camp[0].table[z].saldo_de_gols === camp[0].table[z1].saldo_de_gols
            ) {
              if (
                camp[0].table[z].gols_marcados < camp[0].table[z1].gols_marcados
              ) {
                posicao++;
              } else if (
                camp[0].table[z].gols_marcados ===
                camp[0].table[z1].gols_marcados
              ) {
                if (camp[0].table[z].partidas > camp[0].table[z1].partidas) {
                  posicao++;
                } else if (
                  camp[0].table[z].partidas === camp[0].table[z1].partidas
                ) {
                  //
                }
              }
            }
          }
        }
      }
      camp[0].table[z].posicao = posicao;
    }
  }
});

camp[0].table.sort(function (a, b) {
  return a.posicao - b.posicao;
});

console.log(new Date());

/* API */

app.get("/camp", (req, res) => {
  res.json({ camp });
});

app.get("/rodadas", (req, res) => {
  res.json({ rodadas });
});

app.get("/equipes", (req, res) => {
  res.json({ equipes });
});

export default app;
